/**
 * LINK CONSTANTS
 * @type {string}
 */
export const GAME_INDEX_PENDING = 'GAME_INDEX_PENDING'
export const GAME_INDEX_SUCCESS = 'GAME_INDEX_SUCCESS'
export const GAME_INDEX_FAILURE = 'GAME_INDEX_FAILURE'
export const GAME_INDEX_NO_CONTENT = 'GAME_INDEX_NO_CONTENT'

export const GAME_CREATE_PENDING = 'GAME_CREATE_PENDING'
export const GAME_CREATE_SUCCESS = 'GAME_CREATE_SUCCESS'
export const GAME_CREATE_FAILURE = 'GAME_CREATE_FAILURE'

export const GAME_RESTART_PENDING = 'GAME_RESTART_PENDING'
export const GAME_RESTART_SUCCESS = 'GAME_RESTART_SUCCESS'
export const GAME_RESTART_FAILURE = 'GAME_RESTART_FAILURE'

export const GAME_DELETE_PENDING = 'GAME_DELETE_PENDING'
export const GAME_DELETE_SUCCESS = 'GAME_DELETE_SUCCESS'
export const GAME_DELETE_FAILURE = 'GAME_DELETE_FAILURE'
