/**
 * AUTH CONSTANTS
 * @type {string}
 */
export const AUTH_FORGOT_PENDING = 'AUTH_FORGOT_PENDING'
export const AUTH_FORGOT_SUCCESS = 'AUTH_FORGOT_SUCCESS'
export const AUTH_FORGOT_FAILURE = 'AUTH_FORGOT_FAILURE'

export const AUTH_RESET_PENDING = 'AUTH_RESET_PENDING'
export const AUTH_RESET_SUCCESS = 'AUTH_RESET_SUCCESS'
export const AUTH_RESET_FAILURE = 'AUTH_RESET_FAILURE'
